UPDATE `rainierdev3`.`core_config_data` SET `value`='http://rainier2.upg.com/' WHERE `config_id`='2';
UPDATE `rainierdev3`.`core_config_data` SET `value`='http://rainier2.upg.com/' WHERE `config_id`='3';
UPDATE `rainierdev3`.`core_config_data` SET `value`='http://rainier2.upg.com/' WHERE `config_id`='2676';
UPDATE `rainierdev3`.`core_config_data` SET `value`='http://rainier2.upg.com/' WHERE `config_id`='3531';
UPDATE `rainierdev3`.`core_config_data` SET `value`='http://rainier2.upg.com/' WHERE `config_id`='3532';
UPDATE `rainierdev3`.`core_config_data` SET `value`='http://rainier2.upg.com/admin' WHERE `config_id`='3492';
UPDATE `rainierdev3`.`core_config_data` SET `value`='0' WHERE `config_id`='6';
UPDATE `rainierdev3`.`core_config_data` SET `value`='0' WHERE `config_id`='958';
UPDATE `rainierdev3`.`core_config_data` SET `value`='0' WHERE `config_id`='959';
UPDATE `rainierdev3`.`core_config_data` SET `value`='0' WHERE `config_id`='5';
UPDATE `rainierdev3`.`core_config_data` SET `value`='1' WHERE `config_id`='2885';
UPDATE `rainierdev3`.`wp_options` SET `option_value`='http://rainier2.upg.com/wp' WHERE `option_id`='1';
UPDATE `rainierdev3`.`wp_options` SET `option_value`='http://rainier2.upg.com/blog' WHERE `option_id`='2';
UPDATE `core_config_data` SET `value` = 'localhost' WHERE `core_config_data`.`config_id` = 3258261;

SET FOREIGN_KEY_CHECKS = 0;
-- Truncate Order Tables
use rainierdev3;
TRUNCATE TABLE `gift_message`;
-- TRUNCATE TABLE `reporting_orders`; 
TRUNCATE TABLE `quote`;
TRUNCATE TABLE `quote_address`;
TRUNCATE TABLE `quote_address_item`;
TRUNCATE TABLE `quote_id_mask`;
TRUNCATE TABLE `quote_item`;
TRUNCATE TABLE `quote_item_option`;
TRUNCATE TABLE `quote_payment`;
TRUNCATE TABLE `quote_shipping_rate`;
TRUNCATE TABLE `sales_bestsellers_aggregated_daily`;
TRUNCATE TABLE `sales_bestsellers_aggregated_monthly`;
TRUNCATE TABLE `sales_bestsellers_aggregated_yearly`;
TRUNCATE TABLE `sales_creditmemo`;
TRUNCATE TABLE `sales_creditmemo_comment`;
TRUNCATE TABLE `sales_creditmemo_grid`;
TRUNCATE TABLE `sales_creditmemo_item`;
TRUNCATE TABLE `sales_invoice`;
TRUNCATE TABLE `sales_invoiced_aggregated`;
TRUNCATE TABLE `sales_invoiced_aggregated_order`;
TRUNCATE TABLE `sales_invoice_comment`;
TRUNCATE TABLE `sales_invoice_grid`;
TRUNCATE TABLE `sales_invoice_item`;
TRUNCATE TABLE `sales_order`;
TRUNCATE TABLE `sales_order_address`;
TRUNCATE TABLE `sales_order_aggregated_created`;
TRUNCATE TABLE `sales_order_aggregated_updated`;
TRUNCATE TABLE `sales_order_grid`;
TRUNCATE TABLE `sales_order_item`;
TRUNCATE TABLE `sales_order_payment`;
TRUNCATE TABLE `sales_order_status_history`;
TRUNCATE TABLE `sales_order_tax`;
TRUNCATE TABLE `sales_order_tax_item`;
TRUNCATE TABLE `sales_payment_transaction`;
TRUNCATE TABLE `sales_refunded_aggregated`;
TRUNCATE TABLE `sales_refunded_aggregated_order`;
TRUNCATE TABLE `sales_shipment`;
TRUNCATE TABLE `sales_shipment_comment`;
TRUNCATE TABLE `sales_shipment_grid`;
TRUNCATE TABLE `sales_shipment_item`;
TRUNCATE TABLE `sales_shipment_track`;
TRUNCATE TABLE `sales_shipping_aggregated`;
TRUNCATE TABLE `sales_shipping_aggregated_order`;
TRUNCATE TABLE `tax_order_aggregated_created`;
TRUNCATE TABLE `tax_order_aggregated_updated`;
-- Truncate Customer Tables
TRUNCATE TABLE `customer_address_entity`;
TRUNCATE TABLE `customer_address_entity_datetime`;
TRUNCATE TABLE `customer_address_entity_decimal`;
TRUNCATE TABLE `customer_address_entity_int`;
TRUNCATE TABLE `customer_address_entity_text`;
TRUNCATE TABLE `customer_address_entity_varchar`;
TRUNCATE TABLE `customer_entity`;
TRUNCATE TABLE `customer_entity_datetime`;
TRUNCATE TABLE `customer_entity_decimal`;
TRUNCATE TABLE `customer_entity_int`;
TRUNCATE TABLE `customer_entity_text`;
TRUNCATE TABLE `customer_entity_varchar`;
TRUNCATE TABLE `customer_grid_flat`;
TRUNCATE TABLE `customer_log`;
TRUNCATE TABLE `customer_log`;
TRUNCATE TABLE `customer_visitor`;
TRUNCATE TABLE `newsletter_subscriber`;
TRUNCATE TABLE `persistent_session`;
TRUNCATE TABLE `wishlist`;
TRUNCATE TABLE `wishlist_item`;
TRUNCATE TABLE `wishlist_item_option`;
-- Truncate Review and Search Tables
TRUNCATE TABLE `review`;
TRUNCATE TABLE `review_detail`;
TRUNCATE TABLE `review_entity_summary`;
TRUNCATE TABLE `review_store`;
TRUNCATE TABLE `search_query`;
SET FOREIGN_KEY_CHECKS = 1;