<?php
/**
 * @var $block \Syncit\UIComponent\Block\UIBlock
 */
?>
<div data-bind="scope:'syncit_component'">
    <p data-bind="text:title"></p>
</div>
<script type="text/x-magento-init">
    {
    "*": {
        "Magento_Ui/js/core/app":{
           "components": {
               "syncit_component" : {
                     "component" : "Syncit_UIComponent/js/component",
                     "title": "Terms of service"
               }
           }
        }
    }
    }

</script>
<p><?php echo $block->test()?></p>
